version: '3'
services:
  basic-crud:
    image: basic-crud
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379

  redis:
    image: redis
    ports:
      - 6379:6379
